spring:
  application:
    name: onmoim
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC 드라이버 클래스 이름
    url: ${DEV_DB_URL} # jdbc:mysql://localhost:3306/{데이터베이스명}
    username: ${DEV_DB_USER} # MySQL 유저 이름
    password: ${DEV_DB_PW} # MySQL 비밀번호
  jpa:
    database: mysql # 사용할 데이터베이스 유형 지정 (MySQL)
    database-platform: org.hibernate.dialect.MySQLDialect # Hibernate에서 사용할 MySQL 방언(dialect) 설정
    show-sql: true # 실행된 SQL 쿼리를 콘솔에 출력할지 여부 설정
    hibernate:
      ddl-auto: none # 애플리케이션 실행 시 데이터베이스 스키마의 상태를 설정
    properties:
      hibernate:
        format_sql: true # 출력되는 SQL 쿼리를 보기 좋게 포맷팅
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  # 메일 발송 설정
  mail:
    host: smtp.gmail.com
    port: 587
    accounts:
      - username: "${MAIL_USERNAME_1}"
        password: "${MAIL_PASSWORD_1}"
      - username: "${MAIL_USERNAME_2}"
        password: "${MAIL_PASSWORD_2}"
    properties:
      mail.smtp.auth: "true"
      mail.smtp.starttls.enable: "true"
      mail.smtp.ssl.trust: "smtp.gmail.com"

  cloudflare:
    turnstile:
      secret-key: ${TURNSTILE_SECRET_KEY}
      test-token: ${TEST_TURNSTILE_TOKEN}
      verify-url: https://challenges.cloudflare.com/turnstile/v0/siteverify

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: -1ms
        shutdown-timeout: 100ms

jwt:
  token:
    secretKey: ${JWT_SECRET_KEY}
    expiration:
      access: 3600000
      refresh: 604800000

logging:
  level:
    backend.onmoim.global.security.JwtAuthFilter: DEBUG

minio:
  internal-url: ${MINIO_URL}
  public-url: ${MINIO_PUBLIC_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}